package com.example.android2.model

const val API_KEY = "74c34ef78210a9bc3840d6c543b19fa4"
const val MAIN_INTENT_FILTER = "MAIN INTENT FILTER"
const val MAIN_LOAD_RESULT_EXTRA = "LOAD RESULT"
const val MAIN_DATA_EMPTY_EXTRA = "DATA IS EMPTY"
const val MAIN_RESPONSE_SUCCESS_EXTRA = "RESPONSE SUCCESS"
const val MAIN_REQUEST_ERROR_EXTRA = "REQUEST ERROR"
const val MAIN_REQUEST_ERROR_MESSAGE_EXTRA = "REQUEST ERROR MESSAGE"
const val MAIN_URL_MALFORMED_EXTRA = "URL MALFORMED"
const val MAIN_FILM_LIST_EXTRA = "FILM LIST"
const val PROCESS_ERROR = "PROCESS ERROR"
const val IS_ADULT = "IS ADULT"